### ISSUE TITLE
Bad way to store sources

### ISSUE THREAD

**Issue by guysoft** [Audio-Injector/stereo-and-zero#1]
Hey,
Not sure what you are trying to do,
but storing sources in a deb (aka zip), inside git repo is kinda strange.

**Comment by flatmax** [comment]
Thanks for the first thread on this forum !

Not that uncommon, surely : https://github.com/Hexxeh/rpi-firmware

But you have given me the idea that I should upload the raw code for 
this deb here.

thanks
Matt

**Comment by flatmax** [comment]
I have added the sources for the deb file to the repo.
