### ISSUE TITLE
RPI model B+ Support?

### ISSUE THREAD

**Issue by cdgraff** [Audio-Injector/stereo-and-zero#16]
Hi I buy previously 5 cards and run into RPI Model B, Just I need buy more cards, and I'll like to move to Model B+ the card is working into the new model? need something special?
@flatmax can confirm that is supported? I need buy 10 cards. thanks!

**Comment by cdgraff** [comment]
@flatmax some update on this?

**Comment by cdgraff** [comment]
I tested and work perfect

**Comment by flatmax** [comment]
Great news !
