### ISSUE TITLE
Attach 3.5mm input to the microphone socket on the Zero?

### ISSUE THREAD

**Issue by Finetuned** [Audio-Injector/stereo-and-zero#3]
I'd like to use the microphone connector with different mics so is it possible to attached a 3.5mm input to the mic connector?

If so, can you point me towards a suitable connector...

**Comment by flatmax** [comment]
Which board are you talking about exactly ?

**Comment by Finetuned** [comment]
@flatmax  The Zero

**Comment by flatmax** [comment]
Interesting - ok, I think it is, however the mic. has two connecting pins.. Shown in this image ![this iamge](https://github.com/Audio-Injector/stereo-and-zero/blob/master/issueImages/mic.to.3.5mm.png)

On the zero board, the MicTip connector should be connected to either the RIRCAi or LIRCAi line. The AGND should be conneted to the GNDi pad.
Keep in mind that both power+signal will be on the MicTip. It is possible also that you will get a lot of noise by connecting the mic. in over lines - a bit of experimentation should help to reduce noise.

**Comment by Finetuned** [comment]
Thanks, I'll give it a go.
