### ISSUE TITLE
Question: Multiple cards

### ISSUE THREAD

**Issue by KEClaytor** [Audio-Injector/stereo-and-zero#41]
I have an application which requires four channels of mono audio to be simultaneously sampled.
Is it possible to stack two zero cards on each other and receive data from the L/R line-in inputs from both?
How well synchronized would they be?
Thanks!

**Comment by flatmax** [comment]
Unfortunately not with stereo cards. You need to look at the Audio 
Injector Octo card which can sample up to 6 channels - all synchronised.

**Comment by KEClaytor** [comment]
Thanks for letting me know. The Octo card should be exactly what I need.
