### ISSUE TITLE
Only one channel output on RCA, only one channel output on headphone

### ISSUE THREAD

**Issue by PetGecko** [Audio-Injector/stereo-and-zero#59]
Similar to issue described by StJohn909, but worse, as my headphone also only has one channel output.
Both inputs are fine (recording works).
Is this a hardware problem?

**Comment by flatmax** [comment]
Can you check your alsamixer has both L+R channels turned up. Also a different set of headphpones ?

**Comment by PetGecko** [comment]
Thanks. I tried both. I returned the card as defective.

**Comment by flatmax** [comment]
OK, seems like a reasonable thing to do under the circumstances. Apologies for that problem, very few defective boards slip through our testing procedures - but it looks like this was one of them.
