### ISSUE TITLE
Currently unavailable on Amazon

### ISSUE THREAD

**Issue by syedzayyan** [Audio-Injector/stereo-and-zero#81]

**Comment by flatmax** [comment]
hi - can you try the shop ?
https://shop.audioinjector.net/

**Comment by syedzayyan** [comment]
the shop never loaded for me. I can access the products page but cannot check it out. It waits with a loading indicator for an eternity. I tried three browsers, with and without VPN only to realise some of the JS was not loading.
![Screenshot 2022-11-28 at 08 51 59](https://user-images.githubusercontent.com/44922710/204181300-94925105-3710-4fd1-a214-97e71df0431f.png)

**Comment by flatmax** [comment]
can you clear your cache, remove cookies and force refresh ?

**Comment by flatmax** [comment]
oh hang on - I get the same problem.

**Comment by syedzayyan** [comment]
cleared the site data, removed cookies and forced refresh. same

**Comment by flatmax** [comment]
I just did another test - seems it is working now.

**Comment by syedzayyan** [comment]
I think I placed an order as I have a Paypal receipt, but I also had this dialogue...

![Screenshot 2022-11-28 at 10 23 06](https://user-images.githubusercontent.com/44922710/204193847-45f99ec8-b559-4426-abf1-ac0b8ddccc7a.png)
